[package]
name = "chat_client"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.20", features = ["csr"] }
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["HtmlInputElement", "Window", "Document"] }
wasm-logger = "0.2"
log = "0.4"
eframe = "0.24"
